### PR TITLE
[INIT](Server): Add Route: '/api/places' To Make Google Places API Ca…

### PR DESCRIPTION
**Pull request by Hackmenate**
…ll {NH}

### CODE REVIEW

**Comment by valerieernst** [comment]
That's some good looking ES6

**Review by valerieernst — CHANGES_REQUESTED** [review]
We talked about removing http and https from the apicalls.js file so the app doesn't look for them.

Other than that, looks great!

**Comment by Hackmenate** [comment]
Okay, I removed http/https modules, added Promises and a new /api/details path to get place details based upon placeid.

**Review by valerieernst — APPROVED** [review]

**Review by zeninspire — APPROVED** [review]

**Review by catharp — APPROVED** [review]
much win!

**Pull request merged**
